import { React }  from 'react';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  console.log('test');
  return (
    <div>
      Mi App React
    </div>
  )
}
